# Generated by Django 5.2.3 on 2025-06-21 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RecTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('valor', models.FloatField()),
                ('dia', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DespFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_desp', models.CharField(max_length=40)),
                ('dia', models.PositiveSmallIntegerField()),
                ('valor', models.FloatField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.categoria')),
                ('origem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.origem')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.planejamento')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_loja', models.CharField(max_length=30)),
                ('desc_desp', models.CharField(max_length=40)),
                ('data', models.DateField(auto_now=True)),
                ('valor', models.FloatField()),
                ('parcela_atual', models.PositiveSmallIntegerField(default=0)),
                ('parcelas_total', models.PositiveSmallIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('F', 'Fixa'), ('V', 'Variável')], default='V')),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.categoria')),
                ('origem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.origem')),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.periodo')),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.planejamento')),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('data', models.DateField(auto_now=True)),
                ('valor', models.FloatField()),
                ('periodo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.periodo')),
            ],
        ),
    ]
